### ISSUE TITLE
Add validation to "Main Website" field in "Card" object so that http:// or https:// is required

### ISSUE THREAD

**Issue by crcastle** [fostive/wicked-coolkit-salesforce-app#41]
If someone enters "example.com" with no http:// or https://, the link will show up like this on the trading card: `https://crc-tradingcard.herokuapp.com/example.com` instead of `http://example.com` or `https://example.com`.

For example:
![CleanShot 2021-01-29 at 17 35 40@2x](https://user-images.githubusercontent.com/275734/106336893-dcc04200-625d-11eb-88bc-3c4850f44e92.png)

Maybe also change the field name to "Main Website URL" so that it's clearer that the protocol is required.

**Comment by lukekarrys** [comment]
@crcastle this is something I could on the client as well?

**Comment by crcastle** [comment]
I figured that, but then thought it's best to have clean data from the start than implement rules in code to check for that field coming in multiple formats. It's pretty easy to add a validation rule on a field in salesforce. I've already got it working. I'll create a new package release and update the env var shortly.

**Comment by lukekarrys** [comment]
Cool! I saw from the PR that you can validate that stuff in Salesforce, pretty neat!
